paths:
  /api/external/v1/pets/statistics:
    post:
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PetStatistics'
components:
  schemas:
    PetStatistics:
      type: object
      required:
        - cat
        - dog
      properties:
        cat:
          type: integer
        dog:
          type: integer
